import { useRef, useState } from "react";
import { validateFile } from "@/services/documents/validateFile";
import { extractText } from "@/services/documents/DocumentParser";
import { chunkText } from "@/services/documents/chunker";
import { useSessionStore, type PendingUpload } from "@/stores/sessionStore";
import type { DocType, DocumentChunk, UploadedDocument } from "@/types";

let uploadCounter = 0;
function nextId(prefix: string): string {
  uploadCounter += 1;
  return `${prefix}_${Date.now()}_${uploadCounter}`;
}

/** Storage names are generated by the app, never derived from the user's
 *  filename — see docs/security.md (path traversal). */
function storageFileName(): string {
  return `${crypto.randomUUID()}.txt`;
}

export function DocumentUploader({ docType }: { docType: DocType }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState<"idle" | "parsing" | "done">("idle");

  const activeSessionId = useSessionStore((s) => s.activeSessionId);
  const addPendingUpload = useSessionStore((s) => s.addPendingUpload);
  const addDocumentToSession = useSessionStore((s) => s.addDocumentToSession);

  async function handleFile(file: File) {
    setError(null);
    setStatus("parsing");
    const bytes = new Uint8Array(await file.arrayBuffer());
    const validation = validateFile(file.name, bytes);
    if (!validation.ok || !validation.docType) {
      setError(validation.reason ?? "Invalid file");
      setStatus("idle");
      return;
    }

    try {
      const text = await extractText(validation.docType, bytes);
      const pieces = chunkText(text);
      if (pieces.length === 0) {
        setError("No readable text found in this file");
        setStatus("idle");
        return;
      }

      const documentId = nextId("doc");
      // Uploads on the New Interview screen happen before a session exists,
      // so they are staged as pending and re-keyed onto the session the
      // moment it is created (see sessionStore.createSession).
      const sessionId = activeSessionId ?? "pending";

      const document: UploadedDocument = {
        id: documentId,
        sessionId,
        docType,
        originalFileName: file.name,
        storageFileName: storageFileName(),
        uploadedAtMs: Date.now(),
      };
      const chunks: DocumentChunk[] = pieces.map((piece, index) => ({
        id: nextId("chunk"),
        documentId,
        sessionId,
        docType,
        text: piece,
        order: index,
      }));

      const upload: PendingUpload = { document, chunks };
      if (activeSessionId) addDocumentToSession(activeSessionId, upload);
      else addPendingUpload(upload);

      setFileName(file.name);
      setStatus("done");
    } catch {
      setError("Could not parse file");
      setStatus("idle");
    }
  }

  return (
    <div>
      <button
        type="button"
        onClick={() => inputRef.current?.click()}
        className="input flex items-center justify-between text-left text-ink-muted hover:border-accent/50"
      >
        <span>{fileName ?? "Choose a file (PDF, DOCX, TXT, MD)"}</span>
        {status === "parsing" && <span className="text-xs text-state-thinking">Parsing…</span>}
        {status === "done" && <span className="text-xs text-state-listening">✓</span>}
      </button>
      <input
        ref={inputRef}
        type="file"
        accept=".pdf,.docx,.txt,.md"
        className="hidden"
        onChange={(e) => {
          const file = e.target.files?.[0];
          if (file) void handleFile(file);
        }}
      />
      {error && <p className="mt-1 text-xs text-state-error">{error}</p>}
    </div>
  );
}
